// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Repositories.Models;

namespace Repositories.DBContext;

public partial class CartServiceDBContext : DbContext
{
    public CartServiceDBContext()
    {
    }

    public CartServiceDBContext(DbContextOptions<CartServiceDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<CartItem> CartItems { get; set; }
    public virtual DbSet<UsedService> UsedServices{ get; set; }
    public virtual DbSet<Transaction> Transactions { get; set; }



    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {

        base.OnModelCreating(modelBuilder);
    }

}