services:
  apigateway:
    build:
      context: ./API-Gatewate
      dockerfile: ./API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - planning-service
      - product-service
    networks:
      - backend

  authservice:
    build:
      context: ./AuthService
      dockerfile: ./AuthService/Dockerfile
    ports:
      - "5100:5100"
    networks:
      - backend

  planningservice:
    build:
      context: ./PlanningService
      dockerfile: ./Dockerfile
    ports:
      - "5200:5200"
    networks:
      - backend

  productservice:
    build:
      context: ./API/Dockerfile
    ports:
      - "5300:5300"
    networks:
      - backend


networks:
  backend:
    driver: bridge
