<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="[RemoveLater]\**" />
    <EmbeddedResource Remove="[RemoveLater]\**" />
    <None Remove="[RemoveLater]\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\API-Gateway\SharedLibrary\SharedLibrary.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="RabbitMQ.Client" Version="6.4.0" />
  </ItemGroup>

</Project>
