// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ScheduledEventServiceDbContext))]
    partial class ScheduledEventServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.EventSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("id");

                    b.Property<decimal>("Cost")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("session_cost");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("description");

                    b.Property<int>("Duration")
                        .HasColumnType("INT")
                        .HasColumnName("duration");

                    b.Property<Guid>("EventId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DATETIME")
                        .HasColumnName("last_modified_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("session_start_time");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventSessions");
                });

            modelBuilder.Entity("Domain.Entities.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("name");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("thumbnail_url");

                    b.HasKey("Id");

                    b.ToTable("EventTypes");
                });

            modelBuilder.Entity("Domain.Entities.ScheduledEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(2048)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("DATE")
                        .HasColumnName("end_date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TIME")
                        .HasColumnName("end_time");

                    b.Property<int>("EventStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<int?>("EventTypeId")
                        .HasColumnType("INT")
                        .HasColumnName("event_type_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("location");

                    b.Property<string>("MainColorTag")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(6)")
                        .HasColumnName("main_color_hex");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("name");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("INT")
                        .HasColumnName("number_of_people");

                    b.Property<string>("SecondaryColorTag")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(6)")
                        .HasColumnName("secondary_color_hex");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("DATE")
                        .HasColumnName("start_date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TIME")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Domain.Entities.UsedServices", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CustomerNote")
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("customer_note");

                    b.Property<int>("DamageType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0)
                        .HasColumnName("damage_type");

                    b.Property<DateTime?>("DeliveredTime")
                        .HasColumnType("DATETIME")
                        .HasColumnName("delivered_time");

                    b.Property<string>("InitialCondition")
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("initial_condition");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DATETIME")
                        .HasColumnName("last_modified_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Quantity")
                        .HasColumnType("INT")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("ReturnTime")
                        .HasColumnType("DATETIME")
                        .HasColumnName("returned_time");

                    b.Property<string>("ReturnedCondition")
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("returned_condition");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("service_id");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("service_name");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("session_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("UsedSessionServices");
                });

            modelBuilder.Entity("Domain.Entities.EventSession", b =>
                {
                    b.HasOne("Domain.Entities.ScheduledEvent", null)
                        .WithMany("SessionsNavigation")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.ScheduledEvent", b =>
                {
                    b.HasOne("Domain.Entities.EventType", "EventTypeNavigation")
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EventTypeNavigation");
                });

            modelBuilder.Entity("Domain.Entities.UsedServices", b =>
                {
                    b.HasOne("Domain.Entities.EventSession", null)
                        .WithMany("ServicesNavigation")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.EventSession", b =>
                {
                    b.Navigation("ServicesNavigation");
                });

            modelBuilder.Entity("Domain.Entities.ScheduledEvent", b =>
                {
                    b.Navigation("SessionsNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
