using API.Configuration;
using Ocelot.DependencyInjection;
using Ocelot.Middleware;
var builder = WebApplication.CreateBuilder(args);
builder.Configuration.AddEnvironmentVariables();
builder.Configuration.AddJsonFile("ocelot.json", optional: false, reloadOnChange: true);
builder.Services.AddConfig(builder.Configuration);
var app = builder.Build();
app.UseAuthentication();
app.UseCors("AllowAll");
await app.UseOcelot();
app.Run();