// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class CartItem
{
    public Guid Id { get; set; }

    public Guid CartId { get; set; }

    public Guid ServiceId { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime UpdateDate { get; set; }

    public virtual Cart Cart { get; set; }
}